// <auto-generated />
using Bulk.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bulk.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240205091046_Sabeeth added")]
    partial class Sabeethadded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bulk.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderDisplay")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Models");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Karthi",
                            OrderDisplay = "1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bala",
                            OrderDisplay = "2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Koushi",
                            OrderDisplay = "3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "sabeeth",
                            OrderDisplay = "4"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
